---
title: hugs4bugs
timezone: UTC
collections:
  authors:
    title: Authors
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
name: hugs4bugs
description: hugs4bugs is an open source blog written by shubhendu shubham on various
  cloud and technologies to for community help.
tags:
- blog
- template
- jekyll
- theme
- netlify
show_hero: true
menu:
- title: Home
  url: "/"
- title: About
  url: "/about"
- title: Contact
  url: "/contact"
email: myblackcat420@gmail.com
disqus_username: hugs4bugs
formspree_form_id: formspree_form_id
mailchimp-list: https://hugs4bugs.us1.list-manage.com/subscribe?u=867b91e0eabcef08a2107847c&id=791d7284d0
github_username: sivolko
twitter_username: myselfshubhendu
linkedin_username: shubhendu-shubham
medium_username: shubhendushubham
show_time_bar: true
show_modal_on_exit: false
show_modal_on_finish_post: true
two_columns_layout: true
baseurl: 
url: https://hugs4bugs.me
google_analytics: G-0FMLF6JCFT
language: en
categories_folder: category
sent_message_url: "/contact/message-sent/"
markdown: kramdown
highlighter: rouge
permalink: "/:title/"
paginate_path: "/page/:num/"
show_get_theme_btn: true
use_logo: false
paginate_content:
  enabled: true
  debug: false
  collections:
  - posts
  auto: false
  separator: "--page-break--"
  permalink: "/:num/"
  seo_canonical: true
  properties:
    part:
      is_generated: true
    last:
      is_generated: true
    single:
      is_generated: true
sass:
  style: compressed
plugins:
- jekyll-paginate
- jekyll-paginate-content
exclude:
- package.json
- package-lock.json
- src
- node_modules
- initpost.sh
- Gemfile
- Gemfile.lock
- gulpfile.js
- README.md
